"""empty message

Revision ID: 44388db3fe86
Revises: 4ae5b579aa1c
Create Date: 2022-08-07 14:23:32.946479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44388db3fe86'
down_revision = '4ae5b579aa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('battles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'battles')
    # ### end Alembic commands ###
