"""empty message

Revision ID: afc7ad5eee77
Revises: 44388db3fe86
Create Date: 2022-08-07 18:11:12.275930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc7ad5eee77'
down_revision = '44388db3fe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'battles')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'wins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('battles', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
