"""empty message

Revision ID: f4fe80cf6ae0
Revises: 7915420cb14a
Create Date: 2022-08-06 17:28:09.508836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4fe80cf6ae0'
down_revision = '7915420cb14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_table('pokemon_to_user')
    op.add_column('pokemon', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('exp', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('attk', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('hp', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('defense', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('sprite', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('date_caught', sa.DateTime(), nullable=True))
    op.drop_column('pokemon', 'created_on')
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_exp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.add_column('pokemon', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'date_caught')
    op.drop_column('pokemon', 'sprite')
    op.drop_column('pokemon', 'defense')
    op.drop_column('pokemon', 'hp')
    op.drop_column('pokemon', 'attk')
    op.drop_column('pokemon', 'exp')
    op.drop_column('pokemon', 'ability')
    op.create_table('pokemon_to_user',
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name='pokemon_to_user_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pokemon_to_user_user_id_fkey')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    # ### end Alembic commands ###
